name: Build Ghost and test theme

on: 
  push:
    tags:
      - '*'

jobs:
  install:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      # - name: Easy Zip Files
      #   uses: vimtor/action-zip@v1.2
      #   with:
      #     files: build/ home.txt
      #     dest: ${{ github.workspace }}/example.zip

      - name: '📦 Package windows x64'
        run: |
              cd ${{github.workspace}}
              zip -r example.zip build/*/* home.txt -j
              gh release upload ${{github.event.release.tag_name}} ${{ github.workspace }}/example.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
