name: Build Ghost and test theme

on:
  - push
  - pull_request

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v3
        with:
          version: 8
      - run : echo ${{ github.action_path }}
      - run : echo ${{ github.workspace }}
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1.2
        with:
            files: build/ home.txt
            dest: ${{ github.workspace }}/example.zip
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "build/ home.txt"