name: Build Ghost and test theme

on: 
  push:
    tags:
      - '*'

jobs:
  install:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Easy Zip Files
        uses: vimtor/action-zip@v1.2
        with:
          files: build/ home.txt
          dest: ${{ github.workspace }}/example.zip
      
      - name: Get Release ID
        id: get_release 
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ github.token }}

      # Upload assets to existing release
      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: https://uploads.github.com/repos/${{ github.repository }}/releases/${{ steps.get_release.outputs.id }}/assets{?name,label}
          asset_path: ${{ github.workspace }}/example.zip
          asset_name: example.zip
          asset_content_type: application/zip
