name: Build Ghost and test theme

on: 
  push:
    tags:
      - '*'

jobs:
  install:
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # - name: Easy Zip Files
      #   uses: vimtor/action-zip@v1.2
      #   with:
      #     files: build/ home.txt
      #     dest: ${{ github.workspace }}/example.zip

      - run: pwd
      - run: ls
      - name: 'Upload Asset'
        run: |
              cd ${{github.workspace}}
              zip -r example.zip build/*/* home.txt 
              ls
              gh release upload ${{github.event.release.tag_name}} example.zip
        env:
          GITHUB_TOKEN: ${{ github.TOKEN }}
        shell: bash
